---
title: "Day 4 - Exploring Data"
author: "Amritpal Sandhu"
format: html
editor: visual
---

```{r}

#| warning: false

# If you don't want the output to show but no code
#| echo: false

library(tidyverse)
library(palmerpenguins)
library(GGally)
library(skimr)
```

## Exploratory Data Viz

View("") on the console to see the data set

Check out your data a bit

```{r}

# If you want nothing of the code chunk to show up

#| include: false

#Tell me the column name
names(penguins)

# What are the dimension?
dim(penguins)

# Can you show me the first 6 lines?
head(penguins)

# Can you show me the last 6 lines?
tail(penguins)
```

```{r}
#| echo: false
2+10
```

```{r}
skim(penguins)
```

```{r}
GGally::ggpairs(penguins)
```


## Jitterplot

Flipper length by species

```{r}
#| Flipper
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) + 
  geom_jitter(width = .2, 
              alpha = .5, 
              aes(color = species)) + 
  geom_boxplot(fill = NA) +
  theme_light() +
  scale_color_manual(values = c("darkorchid4", "cyan4", "goldenrod")) + labs(x = "Penguin Species", y = "Flipper Length", title = "Flipper Length vs Species")

```

```{r}
ggplot(data = penguins, aes(x = bill_length_mm)) + 
  geom_histogram(aes(fill = species), color = "magenta") + 
  facet_wrap(~species, ncol = 1)
```

